# Generated by Django 4.2.16 on 2024-09-13 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='language',
        ),
        migrations.AddField(
            model_name='doctor',
            name='languages',
            field=models.ManyToManyField(related_name='doctors', to='doctors.language'),
        ),
    ]
